spring:
  jpa:
    database-platform:org.hivernate.dialect.MYSQL8Dialect
    database: mysql
    properties:
      hibernate:
        jdbc.batch_size: 50
        order_insert: true
        order_update: ture
        format_sql: true
    show-sql: true

    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/naraDB
      username: root
      password: !Biz12341234